name: nx_env

channels:
  - defaults
  - conda-forge
  - pyg

dependencies:
  - python=3.9
  - numpy 
  - pandas 
  - networkx=2.6.2
  - scikit-learn
  - seaborn
  - jupyter
  - matplotlib
  - jupyter_contrib_nbextensions
  - torch
  - torch_geometric
  - torch_sparse
  - pip
  - pip: 
    - jaal
    - cdlib
    - pydot
    - scikit-network