name: nx_env

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.10
  - numpy 
  - pandas 
  - networkx
  - scikit-learn
  - seaborn
  - jupyter
  - matplotlib
  - pip
  - pip: 
    - jaal
    - cdlib
    - pydot